[book]
authors = ["Tulir", "Sky"]
language = "en"
multilingual = false
src = "."
title = "Asgard.Chat"
site-url = "/"

[preprocessor.links]

[output.html]
git-repository-url = "https://github.com/maunium/asgard.chat"
git-repository-icon = "fa-github"
theme = "./theme"

[output.linkcheck]
optional = true
user-agent = "Mozilla/5.0 (X11; Linux x86_64; rv:144.0) Gecko/20100101 Firefox/144.0"
cache-timeout = 604800
exclude = []
traverse-parent-directories = false
